### ISSUE TITLE
Liquid Exception: Unknown tag 'feeds' in _includes/head.html

### ISSUE THREAD

**Issue by taringamberini** [octopress/feeds#17]
After had followed [Usage](https://github.com/octopress/feeds#usage) I have ran:

```
$ jekyll build --trace
Configuration file: /home/.../octopress/_config.yml
/var/lib/gems/1.9.1/gems/rubypants-0.2.0/rubypants.rb:180: warning: already initialized constant VERSION
            Source: source
       Destination: public
      Generating... 
  Liquid Exception: Unknown tag 'feeds' in _includes/head.html, included in _layouts/default.html
/var/lib/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/tags/include.rb:124:in `rescue in render': Unknown tag 'feeds' (Jekyll::Tags::IncludeTagError)
    from /var/lib/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/tags/include.rb:116:in `render'
    from /var/lib/gems/1.9.1/gems/octopress-include-tag-1.1.0/lib/octopress-include-tag.rb:51:in `render'
    from /var/lib/gems/1.9.1/gems/liquid-2.6.2/lib/liquid/block.rb:109:in `block in render_all'
    from /var/lib/gems/1.9.1/gems/liquid-2.6.2/lib/liquid/block.rb:96:in `each'
    from /var/lib/gems/1.9.1/gems/liquid-2.6.2/lib/liquid/block.rb:96:in `render_all'
    from /var/lib/gems/1.9.1/gems/liquid-2.6.2/lib/liquid/block.rb:82:in `render'
    from /var/lib/gems/1.9.1/gems/liquid-2.6.2/lib/liquid/template.rb:128:in `render'
    from /var/lib/gems/1.9.1/gems/liquid-2.6.2/lib/liquid/template.rb:138:in `render!'
    from /var/lib/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:106:in `render_liquid'
    from /var/lib/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:205:in `render_all_layouts'
    from /var/lib/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:239:in `do_layout'
    from /var/lib/gems/1.9.1/gems/octopress-hooks-2.6.0/lib/octopress-hooks.rb:350:in `do_layout'
    from /var/lib/gems/1.9.1/gems/octopress-tag-helpers-1.0.4/lib/octopress-tag-helpers/hooks.rb:9:in `do_layout'
    from /var/lib/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/page.rb:122:in `render'
    from /home/.../octopress/plugins/category_generator.rb:93:in `write_category_index'
    from /home/.../octopress/plugins/category_generator.rb:111:in `block in write_category_indexes'
    from /home/.../octopress/plugins/category_generator.rb:110:in `each'
    from /home/.../octopress/plugins/category_generator.rb:110:in `write_category_indexes'
    from /home/.../octopress/plugins/category_generator.rb:139:in `generate'
    from /var/lib/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/site.rb:280:in `block in generate'
    from /var/lib/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/site.rb:279:in `each'
    from /var/lib/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/site.rb:279:in `generate'
    from /var/lib/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/site.rb:50:in `process'
    from /var/lib/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/command.rb:28:in `process_site'
    from /var/lib/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:56:in `build'
    from /var/lib/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:34:in `process'
    from /var/lib/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
    from /var/lib/gems/1.9.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
    from /var/lib/gems/1.9.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
    from /var/lib/gems/1.9.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
    from /var/lib/gems/1.9.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
    from /var/lib/gems/1.9.1/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
    from /var/lib/gems/1.9.1/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
    from /var/lib/gems/1.9.1/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
    from /usr/local/bin/jekyll:23:in `load'
    from /usr/local/bin/jekyll:23:in `<main>'
```

Thanks,
Tarin

**Comment by imathis** [comment]
I'm sorry, somehow I missed this issue until now. Have you followed the instructions in the [installation](https://github.com/octopress/feeds#installation) section? It seems like somehow Jekyll isn't loading the octopress-feeds plugin.

**Comment by taringamberini** [comment]
> Have you followed the instructions in the installation section?

Yes I have. My gemfile:

```
source "https://rubygems.org"

group :development do
  gem 'rake', '~> 10.0'
  gem 'jekyll', '~> 2.0'
  gem 'octopress-hooks', '~> 2.2'
  gem 'octopress-date-format', '~> 2.0'
  gem 'jekyll-sitemap'
  gem 'rdiscount', '~> 2.0'
  gem 'RedCloth', '~> 4.2.9'
  gem 'haml', '~> 4.0'
  gem 'compass', '~> 1.0.1'
  gem 'sass-globbing', '~> 1.0.0'
  gem 'rubypants', '~> 0.2.0'
  gem 'rb-fsevent', '~> 0.9'
  gem 'stringex', '~> 1.4.0'
end

group :jekyll_plugins do
  gem 'octopress-multilingual'
  gem 'octopress-paginate'
  gem 'octopress-linkblog'
  gem 'octopress-feeds'
end

gem 'sinatra', '~> 1.4.2'
```

After running:

```
$ bundle
```

I get:

```
Resolving dependencies...
Using rake 10.4.2
Using RedCloth 4.2.9
Using blankslate 2.1.2.4
Using hitimes 1.2.2
Using timers 4.0.1
Using celluloid 0.16.0
Using chunky_png 1.3.4
Using fast-stemmer 1.0.2
Using classifier-reborn 2.0.3
Using coffee-script-source 1.9.1.1
Using execjs 2.5.2
Using coffee-script 2.4.1
Using colorator 0.1
Using multi_json 1.11.0
Using sass 3.4.13
Using compass-core 1.0.3
Using compass-import-once 1.0.5
Using rb-fsevent 0.9.4
Using ffi 1.9.8
Using rb-inotify 0.9.5
Using compass 1.0.3
Using tilt 2.0.1
Using haml 4.0.6
Using jekyll-coffeescript 1.0.1
Using jekyll-gist 1.2.1
Using jekyll-paginate 1.1.0
Using jekyll-sass-converter 1.3.0
Using listen 2.10.0
Using jekyll-watch 1.2.1
Using kramdown 1.6.0
Using liquid 2.6.2
Using mercenary 0.3.5
Using posix-spawn 0.3.11
Using yajl-ruby 1.2.1
Using pygments.rb 0.6.3
Using redcarpet 3.2.3
Using safe_yaml 1.0.4
Using parslet 1.5.0
Using toml 0.1.2
Using jekyll 2.5.3
Using jekyll-sitemap 0.8.1
Using json 1.8.2
Using octopress-deploy 1.2.2
Using octopress-hooks 2.6.0
Using octopress-escape-code 2.0.6
Using titlecase 0.1.1
Using octopress 3.0.0.rc.37
Using octopress-date-format 2.0.2
Using rubypants-unicode 0.2.5
Using octopress-filters 1.3.3
Using octopress-tag-helpers 1.0.4
Using octopress-include-tag 1.1.0
Using uglifier 2.7.1
Using octopress-ink 1.0.0.rc.48
Using octopress-return-tag 1.0.1
Using octopress-feeds 2.0.3
Using octopress-linkblog 2.0.1
Using octopress-multilingual 1.2.0
Using octopress-paginate 1.1.2
Using rack 1.6.0
Using rack-protection 1.5.3
Using rdiscount 2.1.8
Using rubypants 0.2.0
Using sass-globbing 1.0.0
Using sinatra 1.4.6
Using stringex 1.4.0
Using bundler 1.8.5
Bundle complete! 18 Gemfile dependencies, 67 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

I'm using Octopress, so before I had installed and configured Octopress as described at:
- [Initial setup](http://octopress.org/docs/setup/)
- [Basic Configuration](http://octopress.org/docs/configuring/)

Another minor inconsistency in Octopress documentation is the following: while in the [Usage](https://github.com/octopress/feeds#usage) page there is:

```
name: Your Site Name
```

in the "Main Configs" section of the page [Basic Configuration](http://octopress.org/docs/configuring/) there is:

```
title:              # Used in the header and title tags
```

I've tryed both `name` and `title` but the error is always present.

Thanks,
Tarin

**Comment by taringamberini** [comment]
The problem has disappeared after reinstalling the full ruby stack.

I'm using octopress under:
- Debian version 7.8 (wheezy) 64 bit
- Kernel Linux 3.2.0-4-amd64
- GNOME 3.4.2

I've removed all my gems and reinstalled all ruby packages, so my ruby version
is:

```
.../octopress(git:source+)$ ruby --version
ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-linux]
```

I've reinstalled octopress, octopress-multilingual plugin, octopress-paginate
plugin and my blog works well.

I've installed octopress-feeds, so after adding it to `Gemfile` I've run:

```
.../octopress(git:source+!?)$ bundle
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 10.4.2
Using RedCloth 4.2.9
Using execjs 2.5.2

Your user account isn't allowed to install to the system Rubygems.
You can cancel this installation and run:

    bundle install --path vendor/bundle

to install the gems into ./vendor/bundle/, or you can enter your password
and install the bundled gems to Rubygems using sudo.

Password: ***************************************************************
Installing autoprefixer-rails 2.2.0.20140804
Using blankslate 2.1.2.4
Using hitimes 1.2.2
Using timers 4.0.1
Using celluloid 0.16.0
Using chunky_png 1.3.4
Using fast-stemmer 1.0.2
Using classifier-reborn 2.0.3
Using coffee-script-source 1.9.1.1
Using coffee-script 2.4.1
Using colorator 0.1
Using multi_json 1.11.2
Using sass 3.4.16
Using compass-core 1.0.3
Using compass-import-once 1.0.5
Using rb-fsevent 0.9.5
Using ffi 1.9.10
Using rb-inotify 0.9.5
Using compass 1.0.3
Using tilt 2.0.1
Using haml 4.0.6
Using jekyll-coffeescript 1.0.1
Using jekyll-gist 1.2.1
Using jekyll-paginate 1.1.0
Using jekyll-sass-converter 1.3.0
Using listen 2.10.1
Using jekyll-watch 1.2.1
Using kramdown 1.8.0
Using liquid 2.6.3
Using mercenary 0.3.5
Using posix-spawn 0.3.11
Using yajl-ruby 1.2.1
Using pygments.rb 0.6.3
Using redcarpet 3.3.2
Using safe_yaml 1.0.4
Using parslet 1.5.0
Using toml 0.1.2
Using jekyll 2.5.3
Using jekyll-sitemap 0.8.1
Installing json 1.8.3 with native extensions
Using octopress-deploy 1.3.0
Using octopress-hooks 2.6.1
Using octopress-escape-code 2.0.6
Using titlecase 0.1.1
Using octopress 3.0.11
Installing octopress-autoprefixer 1.0.1
Using octopress-date-format 2.0.2
Installing rubypants-unicode 0.2.5
Installing octopress-filters 1.3.3
Installing octopress-tag-helpers 1.0.8
Installing octopress-include-tag 1.1.3
Installing uglifier 2.7.1
Installing octopress-ink 1.2.0
Installing octopress-return-tag 1.0.1
Installing octopress-feeds 2.0.4
Using octopress-multilingual 1.2.0
Using octopress-paginate 1.1.2
Using rack 1.6.4
Using rack-protection 1.5.3
Using rdiscount 2.1.8
Using sass-globbing 1.0.0
Using sinatra 1.4.6
Using stringex 1.4.0
Using bundler 1.10.6
Bundle complete! 16 Gemfile dependencies, 67 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

Finally after putting {% feeds %} into `head.html` all works as documented.

So what hasn't been working? Who knows, the only thing I can do is documenting 
here the differences between the old gems installations (above reported)
and the "reinstalled" one:

```
$ diff --side-by-side --suppress-common-lines old.txt reinstalled.txt 
                                    > Using autoprefixer-rails 2.2.0.20140804
Using bundler 1.8.5                 | Using bundler 1.10.6
Using ffi 1.9.8                     | Using ffi 1.9.10
Using json 1.8.2                    | Using json 1.8.3
Using kramdown 1.6.0                | Using kramdown 1.8.0
Using liquid 2.6.2                  | Using liquid 2.6.3
Using listen 2.10.0                 | Using listen 2.10.1
Using multi_json 1.11.0             | Using multi_json 1.11.2
Using octopress 3.0.0.rc.37         | Using octopress 3.0.11
                                    > Using octopress-autoprefixer 1.0.1
Using octopress-deploy 1.2.2        | Using octopress-deploy 1.3.0
Using octopress-feeds 2.0.3         | octopress-feeds 2.0.4
Using octopress-hooks 2.6.0         | octopress-hooks 2.6.1
Using octopress-include-tag 1.1.0   | octopress-include-tag 1.1.3
Using octopress-ink 1.0.0.rc.48     | octopress-ink 1.2.0
Using octopress-linkblog 2.0.1      <
Using octopress-tag-helpers 1.0.4   | octopress-tag-helpers 1.0.8
Using rack 1.6.0                    | Using rack 1.6.4
Using rb-fsevent 0.9.4              | rb-fsevent 0.9.5
Using redcarpet 3.2.3               | redcarpet 3.3.2
Using rubypants 0.2.0               <
Using sass 3.4.13                   | sass 3.4.16
18 Gemfile dep, 67 gems now install | 16 Gemfile dep, 67 gems now install
```

I'll hope this could be useful to someone,
Tarin

**Comment by taringamberini** [comment]
This issue can be closed because all works as documented.
Tarin
