### ISSUE TITLE
Liquid Exception error in article-feed.xml

### ISSUE THREAD

**Issue by justinrummel** [octopress/feeds#9]
I just performed an bundle update that gave me the following updates:
- Installing liquid 2.6.2 (was 2.6.1)
- Installing octopress 3.0.0.rc.30 (was 3.0.0.rc.29)
- Installing octopress-filters 1.2.2 (was 1.2.0)
- Installing octopress-ink 1.0.0.rc.30 (was 1.0.0.rc.29)
- Installing octopress-feeds 1.2.2 (was 1.1.4)

when doing a `jekyll b -c _config.yml,_AccessKeys.yml` I receved this error: 

``` bash
justinrummel@JRummel-MBPr ~/D/G/jr.com-hpstr> jekyll b -c _config.yml,_AccessKeys.yml;
Configuration file: _config.yml
Configuration file: _AccessKeys.yml
            Source: /Users/justinrummel/Documents/GIT/jr.com-hpstr
       Destination: /Users/justinrummel/Documents/GIT/jr.com-hpstr/_site
      Generating... 
  Liquid Exception: undefined method `empty?' for nil:NilClass in article-feed.xml
jekyll 2.5.3 | Error:  undefined method `empty?' for nil:NilClass
```

**Comment by imathis** [comment]
Thanks. I'll take a look!

**Comment by imathis** [comment]
I just ran `bundle update` and the tests still seem to pass just fine. Either this is somehow something funny on your end, or I need to test another scenario that you've found. Could you tell me more about your set up? Try the build again with `--trace` so I can see where the error is coming from?

**Comment by justinrummel** [comment]
My current site is available via this repo: https://github.com/justinrummel/jr.com-hpstr 

Here is the output with --trace:

``` bash
justinrummel@JRummel-MBPr ~/D/G/jr.com-hpstr> jekyll b -c _config.yml,_AccessKeys.yml --trace
Configuration file: _config.yml
Configuration file: _AccessKeys.yml
            Source: /Users/justinrummel/Documents/GIT/jr.com-hpstr
       Destination: /Users/justinrummel/Documents/GIT/jr.com-hpstr/_site
      Generating... 
  Liquid Exception: undefined method `empty?' for nil:NilClass in article-feed.xml
/Library/Ruby/Gems/2.0.0/gems/octopress-feeds-1.2.2/lib/octopress-feeds.rb:53:in `render': undefined method `empty?' for nil:NilClass (NoMethodError)
    from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.2/lib/liquid/block.rb:109:in `block in render_all'
    from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.2/lib/liquid/block.rb:96:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.2/lib/liquid/block.rb:96:in `render_all'
    from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.2/lib/liquid/block.rb:82:in `render'
    from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.2/lib/liquid/template.rb:128:in `render'
    from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.2/lib/liquid/template.rb:138:in `render!'
    from /Library/Ruby/Gems/2.0.0/gems/octopress-include-tag-1.0.3/lib/octopress-include-tag.rb:45:in `block in render'
    from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.2/lib/liquid/context.rb:112:in `stack'
    from /Library/Ruby/Gems/2.0.0/gems/octopress-include-tag-1.0.3/lib/octopress-include-tag.rb:43:in `render'
    from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.2/lib/liquid/block.rb:109:in `block in render_all'
    from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.2/lib/liquid/block.rb:96:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.2/lib/liquid/block.rb:96:in `render_all'
    from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.2/lib/liquid/block.rb:82:in `render'
    from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.2/lib/liquid/block.rb:109:in `block in render_all'
    from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.2/lib/liquid/block.rb:96:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.2/lib/liquid/block.rb:96:in `render_all'
    from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.2/lib/liquid/block.rb:82:in `render'
    from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.2/lib/liquid/template.rb:128:in `render'
    from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.2/lib/liquid/template.rb:138:in `render!'
    from /Library/Ruby/Gems/2.0.0/gems/octopress-include-tag-1.0.3/lib/octopress-include-tag.rb:45:in `block in render'
    from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.2/lib/liquid/context.rb:112:in `stack'
    from /Library/Ruby/Gems/2.0.0/gems/octopress-include-tag-1.0.3/lib/octopress-include-tag.rb:43:in `render'
    from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.2/lib/liquid/block.rb:109:in `block in render_all'
    from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.2/lib/liquid/block.rb:96:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.2/lib/liquid/block.rb:96:in `render_all'
    from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.2/lib/liquid/block.rb:82:in `render'
    from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.2/lib/liquid/template.rb:128:in `render'
    from /Library/Ruby/Gems/2.0.0/gems/liquid-2.6.2/lib/liquid/template.rb:138:in `render!'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:106:in `render_liquid'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:233:in `do_layout'
    from /Library/Ruby/Gems/2.0.0/gems/octopress-hooks-2.3.2/lib/octopress-hooks.rb:292:in `do_layout'
    from /Library/Ruby/Gems/2.0.0/gems/octopress-tag-helpers-1.0.2/lib/octopress-tag-helpers/hooks.rb:9:in `do_layout'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/page.rb:122:in `render'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:298:in `block in render'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:297:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:297:in `render'
    from /Library/Ruby/Gems/2.0.0/gems/octopress-hooks-2.3.2/lib/octopress-hooks.rb:155:in `render'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:51:in `process'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/command.rb:28:in `process_site'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:56:in `build'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:34:in `process'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
    from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
    from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
    from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
    from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
    from /usr/bin/jekyll:23:in `load'
    from /usr/bin/jekyll:23:in `<main>'
justinrummel@JRummel-MBPr ~/D/G/jr.com-hpstr> 
```

**Comment by imathis** [comment]
This looks like you're trying to add link and article feeds without the `octopress-linkblog` plugin. Add `gem 'octopress-linkblog'` to your Gemfile and you should be good to go.

**Comment by justinrummel** [comment]
That was it!  should linkblog be a defined requirement for feeds (just like it installed other gems automatically).

**Comment by imathis** [comment]
No, not really. I don't want to assume people want both plugins. They're compatible but not dependent. It only matters if you try to access `site.articles` or `site.linkposts`. Those variables are created by octopress-linkblog.

I'm curious, where did you see those feed loops? I think they only exist in places where octopress-linkblog is added as a dependency. Just so you know, if you have both octopress-linkblog and octopress-feeds installed, you don't need to add these feeds manually. They're automatically generated if you have link posts or articles.

**Comment by justinrummel** [comment]
I was just playing around with feeds to see how they worked.  I haven't migrated my feedburner source  from /feed.xml file to this format.
